# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Chia-Yu Sun
tagline:          'github page'
description:      "Graduate student in NYCU CS. Welcome to my personal website!"
url:              https://cysun0226.github.io/
baseurl:          https://cysun0226.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cysun0226

plugins:
  - jekyll-gist
